services:
  backend:
    build: ./be
    ports:
      - "3002:3002"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./be/.env
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - CORS_ORIGIN={CORS_ORIGIN}

  frontend:
    build: ./fe/markethub
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3005:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_PASS}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
