export const DASHBOARD_BANNERS = [
  {
    id: 1,
    image: "https://picsum.photos/seed/markethub-1/1600/500",
    title: "Mega Electronics Sale",
    subtitle: "Up to 70% off top brands",
    cta: "Shop now",
    href: "/buyer/category/electronics",
  },
  {
    id: 2,
    image: "https://picsum.photos/seed/markethub-2/1600/500",
    title: "Fashion Week",
    subtitle: "New arrivals from your favourite labels",
    cta: "Explore",
    href: "/buyer/category/fashion",
  },
  {
    id: 3,
    image: "https://picsum.photos/seed/markethub-3/1600/500",
    title: "Home Essentials",
    subtitle: "Upgrade your space, starting at ₹299",
    cta: "Browse",
    href: "/buyer/category/home",
  },
  {
    id: 4,
    image: "https://picsum.photos/seed/markethub-4/1600/500",
    title: "Grocery Deals",
    subtitle: "Free delivery on orders above ₹499",
    cta: "Order now",
    href: "/buyer/category/grocery",
  },
  {
    id: 5,
    image: "https://picsum.photos/seed/markethub-5/1600/500",
    title: "Become a Seller",
    subtitle: "Reach millions of buyers across India",
    cta: "Get started",
    href: "/auth/signup-seller",
  },
];

export const RECOMMENDED_PRODUCTS = [
  {
    id: "rec-1",
    image: "https://picsum.photos/seed/rec-1/600/600",
    title: "Wireless Noise Cancelling Headphones",
    description: "Premium over-ear sound with 30h battery life",
    price: 4999,
    originalPrice: 7999,
    rating: 4.5,
    reviewCount: 1280,
    badge: "Best Seller",
  },
  {
    id: "rec-2",
    image: "https://picsum.photos/seed/rec-2/600/600",
    title: "Smart Fitness Watch Series 6",
    description: "Heart rate, SpO2, GPS tracking",
    price: 3299,
    originalPrice: 4999,
    rating: 4.3,
    reviewCount: 842,
  },
  {
    id: "rec-3",
    image: "https://picsum.photos/seed/rec-3/600/600",
    title: "Ergonomic Office Chair",
    description: "Lumbar support, breathable mesh",
    price: 8499,
    originalPrice: 12999,
    rating: 4.6,
    reviewCount: 312,
    badge: "New",
  },
  {
    id: "rec-4",
    image: "https://picsum.photos/seed/rec-4/600/600",
    title: "Cotton Casual T-Shirt",
    description: "100% organic cotton, regular fit",
    price: 599,
    originalPrice: 999,
    rating: 4.1,
    reviewCount: 2104,
  },
];

export const BEST_DEALS = [
  {
    id: "deal-1",
    image: "https://picsum.photos/seed/deal-1/600/600",
    title: "4K Ultra HD Smart TV — 55 inch",
    price: 32999,
    originalPrice: 54999,
    rating: 4.4,
    reviewCount: 567,
    badge: "Deal of the Day",
  },
  {
    id: "deal-2",
    image: "https://picsum.photos/seed/deal-2/600/600",
    title: "DSLR Camera with 18-55mm Lens",
    price: 28499,
    originalPrice: 41999,
    rating: 4.7,
    reviewCount: 198,
  },
  {
    id: "deal-3",
    image: "https://picsum.photos/seed/deal-3/600/600",
    title: "Robotic Vacuum Cleaner",
    price: 14999,
    originalPrice: 24999,
    rating: 4.2,
    reviewCount: 421,
    badge: "Limited Time",
  },
  {
    id: "deal-4",
    image: "https://picsum.photos/seed/deal-4/600/600",
    title: "Bluetooth Speaker — Waterproof",
    price: 1799,
    originalPrice: 3499,
    rating: 4.5,
    reviewCount: 1567,
    inStock: false,
  },
];

export const USER_PROFILE = {
  id: "u-001",
  role: "buyer",
  firstName: "Ravi",
  lastName: "Malviya",
  email: "ravi1999.rm2110@gmail.com",
  phone: "+91 98765 43210",
  gender: "male",
  dob: "1999-10-21",
  avatar: "https://picsum.photos/seed/avatar-ravi/200/200",
  memberSince: "2024-08-12",
  addresses: [
    {
      id: "addr-1",
      label: "Home",
      name: "Ravi Malviya",
      phone: "+91 98765 43210",
      line1: "203, Sunshine Apartments",
      line2: "MG Road",
      city: "Indore",
      state: "Madhya Pradesh",
      pincode: "452001",
      country: "India",
      isDefault: true,
    },
    {
      id: "addr-2",
      label: "Office",
      name: "Ravi Malviya",
      phone: "+91 98765 43210",
      line1: "Tower B, 4th Floor",
      line2: "Vijay Nagar Tech Park",
      city: "Indore",
      state: "Madhya Pradesh",
      pincode: "452010",
      country: "India",
      isDefault: false,
    },
  ],
};

export const BUYER_ORDERS = [
  {
    id: "ORD-2026-00148",
    placedAt: "2026-05-22T11:14:00.000Z",
    status: "delivered",
    deliveredAt: "2026-05-24T18:32:00.000Z",
    paymentMethod: "UPI",
    addressLabel: "Home",
    items: [
      {
        id: "rec-1",
        image: "https://picsum.photos/seed/rec-1/600/600",
        title: "Wireless Noise Cancelling Headphones",
        seller: "Sony Official Store",
        price: 4999,
        quantity: 1,
      },
      {
        id: "rec-4",
        image: "https://picsum.photos/seed/rec-4/600/600",
        title: "Cotton Casual T-Shirt",
        seller: "Urban Threads",
        price: 599,
        quantity: 2,
      },
    ],
    subtotal: 6197,
    shipping: 0,
    total: 6197,
  },
  {
    id: "ORD-2026-00139",
    placedAt: "2026-05-18T09:02:00.000Z",
    status: "shipped",
    expectedBy: "2026-05-28T00:00:00.000Z",
    trackingId: "BLD3984712IN",
    paymentMethod: "Credit Card",
    addressLabel: "Office",
    items: [
      {
        id: "deal-1",
        image: "https://picsum.photos/seed/deal-1/600/600",
        title: "4K Ultra HD Smart TV — 55 inch",
        seller: "MegaMart Electronics",
        price: 32999,
        quantity: 1,
      },
    ],
    subtotal: 32999,
    shipping: 0,
    total: 32999,
  },
  {
    id: "ORD-2026-00131",
    placedAt: "2026-05-14T17:46:00.000Z",
    status: "confirmed",
    expectedBy: "2026-05-30T00:00:00.000Z",
    paymentMethod: "Cash on Delivery",
    addressLabel: "Home",
    items: [
      {
        id: "rec-3",
        image: "https://picsum.photos/seed/rec-3/600/600",
        title: "Ergonomic Office Chair",
        seller: "WorkWell Furniture",
        price: 8499,
        quantity: 1,
      },
    ],
    subtotal: 8499,
    shipping: 199,
    total: 8698,
  },
  {
    id: "ORD-2026-00124",
    placedAt: "2026-05-09T13:21:00.000Z",
    status: "pending",
    paymentMethod: "UPI",
    addressLabel: "Home",
    items: [
      {
        id: "rec-2",
        image: "https://picsum.photos/seed/rec-2/600/600",
        title: "Smart Fitness Watch Series 6",
        seller: "TimePiece Co.",
        price: 3299,
        quantity: 1,
      },
    ],
    subtotal: 3299,
    shipping: 0,
    total: 3299,
  },
  {
    id: "ORD-2026-00102",
    placedAt: "2026-04-26T08:18:00.000Z",
    status: "cancelled",
    cancelledAt: "2026-04-27T10:02:00.000Z",
    paymentMethod: "Credit Card",
    addressLabel: "Home",
    items: [
      {
        id: "deal-4",
        image: "https://picsum.photos/seed/deal-4/600/600",
        title: "Bluetooth Speaker — Waterproof",
        seller: "BoomBox Audio",
        price: 1799,
        quantity: 1,
      },
    ],
    subtotal: 1799,
    shipping: 0,
    total: 1799,
  },
  {
    id: "ORD-2026-00097",
    placedAt: "2026-04-12T15:55:00.000Z",
    status: "returned",
    returnedAt: "2026-04-22T12:10:00.000Z",
    paymentMethod: "UPI",
    addressLabel: "Office",
    items: [
      {
        id: "deal-3",
        image: "https://picsum.photos/seed/deal-3/600/600",
        title: "Robotic Vacuum Cleaner",
        seller: "HomeBot",
        price: 14999,
        quantity: 1,
      },
    ],
    subtotal: 14999,
    shipping: 0,
    total: 14999,
  },
];

export const BRAND_HIGHLIGHTS = [
  { id: "brand-1", name: "Sony", image: "https://picsum.photos/seed/brand-sony/200/200", tagline: "Up to 40% off" },
  { id: "brand-2", name: "Nike", image: "https://picsum.photos/seed/brand-nike/200/200", tagline: "New arrivals" },
  { id: "brand-3", name: "Apple", image: "https://picsum.photos/seed/brand-apple/200/200", tagline: "Latest lineup" },
  { id: "brand-4", name: "Samsung", image: "https://picsum.photos/seed/brand-samsung/200/200", tagline: "Mega savings" },
  { id: "brand-5", name: "Boat", image: "https://picsum.photos/seed/brand-boat/200/200", tagline: "Audio fest" },
  { id: "brand-6", name: "Adidas", image: "https://picsum.photos/seed/brand-adidas/200/200", tagline: "Sportswear" },
];
