CREATE TABLE IF NOT EXISTS categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    parentId INT NULL,
    displayName VARCHAR(50) NOT NULL,
    imageUrl VARCHAR(255),
    slug VARCHAR(255),
    FOREIGN KEY (parentId) REFERENCES categories(id) ON DELETE SET NULL,
    isActive BOOLEAN DEFAULT FALSE,
    createdBy VARCHAR(255) NOT NULL,
    updatedBy VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP 
)