CREATE TABLE IF NOT EXISTS banners(
    id INT AUTO_INCREMENT PRIMARY KEY,
    bannerName VARCHAR(255) NOT NULL,
    bannerImageUrl VARCHAR(255) NOT NULL,
    bannerLink VARCHAR(255) NOT NULL,
    bannerOrder TINYINT DEFAULT AUTO_INCREMENT NOT NULL,
    createdBy VARCHAR(255) NOT NULL,
    updatedBy VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isActive BOOLEAN NOT NULL DEFAULT FALSE,
)