CREATE TABLE IF NOT EXISTS banners (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    subtitle VARCHAR(255) NOT NULL,
    imageUrl VARCHAR(255) NOT NULL,
    ctaText VARCHAR(50) NOT NULL,
    ctaLink VARCHAR(255) NOT NULL,
    displayOrder TINYINT NOT NULL DEFAULT 0,
    categoryId INT NULL,
    createdBy VARCHAR(255) NOT NULL,
    updatedBy VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isActive BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (categoryId) REFERENCES categories(id)
);
